### ISSUE TITLE
안녕하세요. 파이썬 딥러닝 텐서플로 p320 코딩 문의! (강의 관련)

### ISSUE THREAD

**Issue by jasonyim2** [lovedlim/tensorflow#10]
안녕하세요. 

좋은 책을 집필하여 주셔서 즐겁게 읽었습니다. 제가 최근에 이 책을 교재로 교육기관에서 강의를 실시했습니다.
다만, P320에 있는 두 번째 파란 박스의 프로그래밍 구문을 실시하면 자료가 불러들여지지 않고 에러가 발생했습니다. 

from Korpora import KoreanChatbotKorpus
corpus = KoreanChatbotKorpus()

저는 이 책의 코딩을 github에서 제공하는대로 그대로 실행했기 때문에 제가 코딩 오타를 치지는 않았습니다.
제 판단에는 책을 집필하실 때는 이런 에러가 발생하지 않았는데 
9월 들어 원래 이 자료를 제공하는 Repository 사이트에 뭔가 문제가 생긴 것 같습니다.

다음에도 이 책으로 강의를 진행하고자 해서 
P320 페이지의 자료 로딩 중 에러 문제를 한 번 봐 주시고 해결책을 알려주시면 감사하겠습니다. 
참고로 당연히 바로 앞에
!pip install korpora 도 문제없이 잘 돌아갔고요. 저는 구글 코랩에서 코딩을 실행했습니다. 

(아마 원 Repository 쪽 문제인 것 같은데) 이 문제를 해결해주시면 감사드리겠습니다.
 
전체적으로 책을 이해가 쉽게 간략하게 써주셔서 이해가 쉬웠습니다. 감사합니다.

**Comment by lovedlim** [comment]
안녕하세요! 
우선 저희 책을 활용해 주셔서 감사합니다 :) 

말씀해주신 내용이 아래 이슈와 같은 내용으로 보여집니다.
https://github.com/lovedlim/tensorflow/issues/8

--------- 링크 내용 ---------
Korpora PYPI 서버에 오류가 있어 보입니다.
원본 데이터셋의 raw 데이터를 직접 읽어와서 진행하실 수 있습니다.
work-around 하실 수 있는 코랩 예제파일의 링크를 공유 드리겠습니다. 수정된 코드를 참고해 주세요.

링크:
https://colab.research.google.com/drive/1c8DVe5lkMaJn6nUkmjVaNIom4FgKUqAi?usp=sharing

감사합니다!

**Comment by jasonyim2** [comment]
감사합니다. 수정해주신 코딩이 잘 돌아가는 것을 확인했습니다.
