### ISSUE TITLE
4.5.2_simple_yolo.ipynb 에러

### ISSUE THREAD

**Issue by acumox** [lovedlim/tensorflow#11]
안녕하세요
4.5.2_simple_yolo.ipynb
# 랜덤하게 도형을 그리고, 실제 정답 값을 생성하는 함수 정의
# 0.png / 1.png / 2.png 파일이 필요함
이 부분 실행하니 아래와 같은 에러가 나옵니다. 해결책을 알려주시면 감사하겠습니다.

error                                     Traceback (most recent call last)
<ipython-input-2-3d7b9083bc22> in <module>()
     43     return img,label
     44 
---> 45 img,label = make_img_label()
     46 cv2_imshow(img)

<ipython-input-2-3d7b9083bc22> in make_img_label()
     34             input_img = cv2.resize(img_0,(w,h))
     35         if(shape_type==1):
---> 36             input_img = cv2.resize(img_1,(w,h))
     37         if(shape_type==2):
     38             input_img = cv2.resize(img_2,(w,h))

error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/resize.cpp:3720: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

**Comment by HongJaeKwon** [comment]
안녕하세요
질문해 주셔서 감사합니다.
해당 이미지 파일들은 배포된 코드에 함께 들어가 있습니다.
![image](https://user-images.githubusercontent.com/44965354/136956006-df1d3c10-500e-4064-9999-1d3bf8693541.png)
위 업로드 버튼을 이용하여 코랩에 업로드하고 실행하면 해결될 것 같습니다.
감사합니다.

**Comment by acumox** [comment]
선생님
알려주신 대로 하니 잘 됩니다.
대단히 감사합니다

*좋은 책 출판해 주셔서 너무 감사드립니다.

**Comment by HongJaeKwon** [comment]
책을 봐주시고, 또 코드를 직접 실행하면서 질문해 주셔서 감사합니다!
