### ISSUE TITLE
4.4_cats_and_dogs_data_processing.ipynb 에러

### ISSUE THREAD

**Issue by acumox** [lovedlim/tensorflow#12]
안녕하세요
4.4_cats_and_dogs_data_processing.ipynb
# 샘플 이미지 출력

이 부분 실행하니 아래와 같은 에러가 나옵니다. 해결책을 알려주시면 감사하겠습니다.
IndexError                                Traceback (most recent call last)
<ipython-input-14-4e35875d3335> in <module>()
      8 
      9     ax = plt.subplot(4, 8, i + 1)
---> 10     plt.imshow(images[i])
     11     plt.title(class_labels[labels[i].astype(np.int)])
     12     plt.axis("off")

IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by HongJaeKwon** [comment]
이 에러 또한 데이터 파일(zip 파일)이 로드되지 않아 생긴 문제로 보입니다.
자료실에서 자료를 다운받아 압축을 제대로 풀어주면 해결될 것 같습니다.
책 206 페이지를 참조하면 자세한 내용이 나와 있습니다.
감사합니다.

**Comment by acumox** [comment]
선생님
알려주신 대로 하니 잘 됩니다.
대단히 감사합니다
*좋은 책 출판해 주셔서 너무 감사드립니다.

**Comment by HongJaeKwon** [comment]
책을 봐주시고, 또 코드를 직접 실행하면서 질문해 주셔서 감사합니다!
