### ISSUE TITLE
4.10. Grad_CAM.ipynb 질문입니다

### ISSUE THREAD

**Issue by acumox** [lovedlim/tensorflow#13]
안녕하세요
4.10. Grad_CAM.ipynb 에서
# 개와 고양이가 함께 있는 사진을 불러오고 그려준다
img = cv2.imread('animals.jpg')

사진 업로드가 안 됩니다.
사진을 코랩의 어느 폴더에 두고 불러야 하는지요?

**Comment by qmfforqhfl** [comment]
작업중이신 코랩 노트북 파일과 같은 위치에 파일을 업로드하신 후에 다시 시도해보시면 좋을 것 같습니다!

**Comment by acumox** [comment]
감사합니다
