### ISSUE TITLE
4.3_eurosat_augmentation 데이터셋 로드 에러 

### ISSUE THREAD

**Issue by qualis2006** [lovedlim/tensorflow#14]
위성 사진 데이터셋  로드할 때 Timeout Error가 나옵니다.
(train_ds, valid_ds), info = tfds.load('eurosat/rgb', split=['train[:80%]', 'train[80%:]'],
                                        shuffle_files=True, 
                                        as_supervised=True,
                                        with_info=True,
                                        data_dir=DATA_DIR)

=====================
TimeoutError                              Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/urllib3/connection.py in _new_conn(self)
    158             conn = connection.create_connection(
--> 159                 (self._dns_host, self.port), self.timeout, **extra_kw)
    160 
  .
  .
  .
ConnectionError: HTTPConnectionPool(host='madm.dfki.de', port=80): Max retries exceeded with url: /files/sentinel/EuroSAT.zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbb6b83c10>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by lovedlim** [comment]
안녕하세요! :) 정상적으로 데이터셋 로드됨을 방금 확인했는데 혹 다시 해봐도 동일 증상일까요?

**Comment by qualis2006** [comment]
네 질문을 올릴 당시에 약 1 주일(?)간 Time Error가 났던 것 같습니다.  아마도 Eurosat 사이트에 문제가 있었지 않았나 합니다. 그 후에는 정상적으로 데이터셋 로드되는 걸 확인했습니다. 당시에 다른 데이터셋 로드 되는 것 확인했는데 Eurosat 데이터 셋 TImeout 에러가 나온 것이 여전히 궁금하기는 합니다.

**Comment by lovedlim** [comment]
아하!! 넵!! ㅠ 그랬군요!!! 문제가 있었나 보네요~ 알려주셔서 감사합니다!!! 열공하세요 :)

**Comment by qualis2006** [comment]
네, 좋은 책 덕분에 열공(?)하고 있습니다.
