### ISSUE TITLE
5.5_seq2seq.ipynb 에러 (KoreanChatbotKorpus() 호출 시)

### ISSUE THREAD

**Issue by qualis2006** [lovedlim/tensorflow#17]
KoreanChatbotKorpus() 호출할 때  아래와 같이 "HTTPError: HTTP Error 404: Not Found" 에러가 나옵니다. 

# 챗봇 라이브러리 불러오기
from Korpora import KoreanChatbotKorpus
corpus = KoreanChatbotKorpus()

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-13-94b2bdf88166> in <module>()
      1 # 챗봇 라이브러리 불러오기
      2 from Korpora import KoreanChatbotKorpus
----> 3 corpus = KoreanChatbotKorpus()

9 frames
/usr/lib/python3.7/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    647 class HTTPDefaultErrorHandler(BaseHandler):
    648     def http_error_default(self, req, fp, code, msg, hdrs):
--> 649         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    650 
    651 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 404: Not Found

**Comment by teddylee777** [comment]
#8 

이슈를 확인해 주시면 될 것 같습니다
해결 방안에 대한 내용을 colab 파일로도 공유해놓았으며 해당 issue 안에서 확인하실 수 있습니다.

감사합니다.

**Comment by qualis2006** [comment]
네, #8 이슈이네요. 감사합니다
