### ISSUE TITLE
4-2-8 KoBERT 토크나이저 코드 오류 문의

### ISSUE THREAD

**Issue by Shin-JK** [lovedlim/tensorflow#18]
안녕하세요.
4-2-8 KoBERT토크나이저 소스코드( 307페이지) 중

_**from kobert.utils import get_tokenizer**_

위 구문에서 아래와 같은 오류가 발생합니다.

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-43-72fdbea1a7b0> in <module>()
      1 from gluonnlp.data import SentencepieceTokenizer
----> 2 from kobert.utils import get_tokenizer
      3 tok_path = get_tokenizer()
      4 sp  = SentencepieceTokenizer(tok_path)
      5 print(sp('영실아오늘날씨어때?'))

12 frames
/content/Mecab-ko-for-Google-Colab/KoBERT/kobert/__init__.py in <module>()
     14 # limitations under the License.
     15 
---> 16 from kobert.utils.utils import download, get_tokenizer
     17 from kobert.pytorch_kobert import get_pytorch_kobert_model
     18 from kobert.mxnet_kobert import get_mxnet_kobert_model

/content/Mecab-ko-for-Google-Colab/KoBERT/kobert/utils/__init__.py in <module>()
----> 1 from kobert.utils.utils import download, get_tokenizer

/content/Mecab-ko-for-Google-Colab/KoBERT/kobert/utils/utils.py in <module>()
     17 import os
     18 
---> 19 from kobert.utils.aws_s3_downloader import AwsS3Downloader
     20 
     21 

/content/Mecab-ko-for-Google-Colab/KoBERT/kobert/utils/aws_s3_downloader.py in <module>()
----> 1 import boto3
      2 import os
      3 import sys
      4 from botocore import UNSIGNED
      5 from botocore.client import Config

/usr/local/lib/python3.7/dist-packages/boto3/__init__.py in <module>()
     14 import logging
     15 
---> 16 from boto3.session import Session
     17 from boto3.compat import _warn_deprecated_python
     18 

/usr/local/lib/python3.7/dist-packages/boto3/session.py in <module>()
     15 import os
     16 
---> 17 import botocore.session
     18 from botocore.client import Config
     19 from botocore.exceptions import DataNotFoundError, UnknownServiceError

/usr/local/lib/python3.7/dist-packages/botocore/session.py in <module>()
     27 from botocore import UNSIGNED
     28 import botocore.configloader
---> 29 import botocore.credentials
     30 import botocore.client
     31 from botocore.configprovider import ConfigValueStore

/usr/local/lib/python3.7/dist-packages/botocore/credentials.py in <module>()
     33 from botocore.compat import total_seconds
     34 from botocore.compat import compat_shell_split
---> 35 from botocore.config import Config
     36 from botocore.exceptions import UnknownCredentialError
     37 from botocore.exceptions import PartialCredentialsError

/usr/local/lib/python3.7/dist-packages/botocore/config.py in <module>()
     14 from botocore.compat import OrderedDict
     15 
---> 16 from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
     17 from botocore.exceptions import InvalidS3AddressingStyleError
     18 from botocore.exceptions import InvalidRetryConfigurationError

/usr/local/lib/python3.7/dist-packages/botocore/endpoint.py in <module>()
     20 from botocore.vendored import six
     21 
---> 22 from botocore.awsrequest import create_request_object
     23 from botocore.exceptions import HTTPClientError
     24 from botocore.httpsession import URLLib3Session

/usr/local/lib/python3.7/dist-packages/botocore/awsrequest.py in <module>()
     22 from urllib3.connectionpool import HTTPSConnectionPool
     23 
---> 24 import botocore.utils
     25 from botocore.compat import six
     26 from botocore.compat import (

/usr/local/lib/python3.7/dist-packages/botocore/utils.py in <module>()
     30 import botocore
     31 import botocore.awsrequest
---> 32 import botocore.httpsession
     33 from botocore.compat import (
     34     json, quote, zip_longest, urlsplit, urlunsplit, OrderedDict,

/usr/local/lib/python3.7/dist-packages/botocore/httpsession.py in <module>()
      8 from urllib3 import PoolManager, proxy_from_url, Timeout
      9 from urllib3.util.retry import Retry
---> 10 from urllib3.util.ssl_ import (
     11     ssl, OP_NO_SSLv2, OP_NO_SSLv3, OP_NO_COMPRESSION,
     12     PROTOCOL_TLS, DEFAULT_CIPHERS,

ImportError: cannot import name 'PROTOCOL_TLS' from 'urllib3.util.ssl_' (/usr/local/lib/python3.7/dist-packages/urllib3/util/ssl_.py)

**Comment by teddylee777** [comment]
@Shin-JK 님 안녕하세요?

해결책을 찾아서 공유 드립니다.

먼저 최하단에 보시면 다음과 같은 코드가 있습니다.
urllib3 버전을 최신으로 업데이트 해주셔야 하기 때문에 아래 코드를 실행하여 업그레이드 후

```python
# urllib3 설치 후
# 런타임 - 런타임 다시 시작 버튼 클릭
!pip install --upgrade urllib3
```

코랩의 상단 "런타임" - "런타임 다시 시작" 버튼을 눌러 재시작 해주세요.
그런 다음 

`from kobert.utils import get_tokenizer` 코드를 실행하시면 오류가 발생하지 않습니다.

urllib3 패키지는 업그레이드 후 코랩을 다시 시작해주셔야 하는데, 다시 시작 해주지 않으면 동일 에러가 발생하게 됩니다.
근본적인 해결책은 아니지만, 일시적으로 패키지 dependency 충돌로 발생한 에러처럼 보이며,
조만간 colab 인스턴스도 업데이트가 되면 해결되리라 기대합니다.

[Kobert Issue 코랩파일 링크](https://colab.research.google.com/drive/1WiWfusVPv0lQIxW-i4OlOiP8-NfU9F0w?usp=sharing)

감사합니다.
