### ISSUE TITLE
P.152 CNN 예제에 대해서 질문

### ISSUE THREAD

**Issue by djdjdols** [lovedlim/tensorflow#19]
수고하십니다.
아직 파이썬 및 텐서플로의 초보자이다보니
나온 예제를 그대로 따라하면서, 제가 만들고자 하는 영역에 적용중입니다.

다름이 아니오라
P.152에 나와있는 예제입니다만,
트레이닝에 60,000개의 파일?을 가지고 P.153에서 훈련시키는 걸로 이해 했습니다만,
이 책의 내용대로라면, 60,000개의 파일중 몇개를 훈련시키는건지 잘 이해를 못했습니다.

만약, 트레이닝 데이터 전체를 다 훈련시킨다 가정한다면
어느부분에 60,000을 추가 입력을 해야하는지 알려주시면 대단히 감사하겠습니다.

**Comment by lovedlim** [comment]
안녕하세요 😁
6만개 파일 모두 훈련하는 것입니다.
다만 이미지를 불러오는 단위가 32개(기본 배치 사이즈)로 설정되어 
60,000 / 32 = 1,875라는 숫자라 보입니다.

**Comment by djdjdols** [comment]
> 안녕하세요 😁 6만개 파일 모두 훈련하는 것입니다. 다만 이미지를 불러오는 단위가 32개(기본 배치 사이즈)로 설정되어 60,000 / 32 = 1,875라는 숫자라 보입니다.

 수고하십니다. 바쁘신 와중에 이렇게 답변 주셔서 고맙습니다. 
설명해주신 내용에 대해서 이해 되었습니다. 앞으로도 잘 부탁드리겠습니다.
