### ISSUE TITLE
데이터 훈련 시 epoch 아래 000/000 숫자가 무엇인가요

### ISSUE THREAD

**Issue by tlsthk** [lovedlim/tensorflow#20]
텐서플로 훈련 시 에포크 아래 있는 숫자의 의미가 무엇인가요

**Comment by tlsthk** [comment]
247페이지 입니다!

**Comment by lovedlim** [comment]
안녕하세요 :) 딥러닝 학습할 때 000/000을 자주 보게 되요! 텐서플로 배치사이즈(학습 단위)로 연산을 수행하고 가중치를 업데이트 해요 
만약 데이터가 1024개 이고 배치사이즈가 64일때 1 epoch 마다 가중치가 16번씩 업데이트 되겠네요! 
또한 배치사이즈는 튜닝가능하며 기본값은 32 입니다 👍
