### ISSUE TITLE
ground true 값이 무엇인가요

### ISSUE THREAD

**Issue by tlsthk** [lovedlim/tensorflow#21]
262페이지
ground true 값은 무엇이며 
변수들을 나열하고 \ 역슬래시 표시가 무슨 뜻인지 궁금합니다.

**Comment by teddylee777** [comment]
ground true: 정답값을 의미합니다.
\ 역슬래시는 python에서 다음 줄에 코드를 이어 작성할 때 사용하는 문법입니다.
