### ISSUE TITLE
p.268 질문이요!

### ISSUE THREAD

**Issue by tlsthk** [lovedlim/tensorflow#22]
grad cam 모델은 vgg 16 모델의 입력과 출력을 그대로 사용하면서 
마지막 합성곱층(block5_conv3)의 출력을 grad cam 모델의 두 번째 출력으로 추가한다고 되어 있는데..

268 페이지 코드에 output 설정 부분에 왜 block5_conv3이 먼저 나오는 건가요?
그리고 모델 생성된 것을 그림으로 나타내는 걸 해봤는데 vgg model과 grad_cam_model의 차이가 뭔지 모르겠습니다..

마지막으로 tf.keras.models이랑 tf.keras.models.Model 의 차이점이 무엇인가요??

**Comment by teddylee777** [comment]
tf.keras.models.Model은 tf.keras.models을 레퍼런싱(참조) 합니다.
즉 같은 객체입니다. 따라서 동일 객체로 생각하시면 됩니다.

**Comment by tlsthk** [comment]
감사합니다! 그 위에 관련된 답변도 알고 싶습니다!!

**Comment by HongJaeKwon** [comment]
안녕하세요. 질문 주셔서 너무 감사합니다.

268 페이지 코드에 output 설정 부분에 왜 block5_conv3이 먼저 나오는 건가요?
-> 순서는 전혀 상관없습니다.
  단지 모델에 인풋을 넣고 출력값을 변수에 담을때, 우리가 지정한 순서로 값이 리턴된다는 점만 알고 있으면 됩니다.
  ( 말씀해 주신 코드 바로 아래 함수 결과값을 저장한 순서를 잘 보시면 될 것 같습니다.)

모델 생성된 것을 그림으로 나타내는 걸 해봤는데 vgg model과 grad_cam_model의 차이가 뭔지 모르겠습니다..
-> 그림으로 나타낸다는 뜻이 제가 예상할 땐 "plot_model" 함수를 사용항 것으로 이해되는데, 
결론을 말씀 드리면 둘은 같은 모델이 맞습니다.
 단지 중간의 출력층의 결과를 쉽게 얻기 위해 따로 모델로 지정한 것 뿐입니다.
