### ISSUE TITLE
188p 질문입니다!

### ISSUE THREAD

**Issue by tlsthk** [lovedlim/tensorflow#23]
1. 우선 위성사진 데이터셋을 불러올 때 왜 굳이 메타정보도 같이 불러 오는건가요?

2. 그다음으로 188페이지 보시면 코드에서 사용자 정의 함수를 정의하고 있는데 map 함수 사용 예를 보여주기 위해 전처리를 하는 걸 함수로 만든건가요?? 왜 사용자 정의 함수를 만든 건지 궁금합니다
이전 mnist 예제에서는 전처리를 할 때 그냥 x_train /255 이런 식으로 했는데
이 위성 데이터셋도 train_ds/255 라고 하면 안 되는건가요??

3. 마지막으로 만든 사용자정의함수에서 만약 label 값을 같이 넘기지 않으면 안 되나요?
같이 넘기지 않았다면 어떻게 될까요?

**Comment by tsdata** [comment]
안녕하세요. 다음과 같이 답변 드립니다. 
1. 메타정보는 데이터셋에 대한 정보를 확인하기 위해서 불러왔습니다.
2. 이미지에 대한 전처리를 배치 단위로 처리하기 위해서 사용자 함수를 사용합니다. 196페이지의 data_augmentation 함수로 연계하기 위하여, 188페이지에서 간략한 내용으로 먼저 제시하였습니다. 
3. 텐서플로 데이터셋은 (features, labels) 형식으로 투플 구조입니다. 따라서, image와 label을 구분하여 처리한 뒤에 넘겨주어야 합니다.
