### ISSUE TITLE
두 가지 질문 드립니다. (1. 입력 레이어 노드 개수 2. transformer로 다중 분류 모델 만드는 방법)

### ISSUE THREAD

**Issue by GentleKM** [lovedlim/tensorflow#24]
먼저 좋은 책 써 주셔서 감사 드리고, 공부하는데 큰 도움이 되었습니다.
두 가지 질문 드립니다.

1. 입력 레이어의 노드 개수 또한 히든 레이어와 같이 랜덤으로 정하는 건가요? 혹시 저자님들만의 팁이 있으시면 알려주실 수 있을까요?

2. 341 페이지에 transformer를 활용해서 긍정, 부정 감성분석 예제가 있던데요. 이 예제를 클래스가 10개 정도 되는 분류 모델을 만드는 데도  활용할 수 있을까요? 가능하다면 대략적으로 어느 부분을 modify 하면 될 지 알려주시면 감사하겠습니다.

감사합니다.

**Comment by teddylee777** [comment]
1. 랜덤이 맞긴합니다. 다만, 논문에서 가이드 하고 있는 노드와 히든 레이어의 구조도를 참고하는 편입니다. SOTA(State of the Art) 모델을 검색하여 해당 구조도를 차용하거나 가장 많이 활용하는 방법은 pre-trained된 모델을 가져와서 사용하는 경우도 많습니다. 경진대회 같은 경우는 수많은 실험을 통해 모델을 구축하기도 합니다.
2. 감정 분석 모델은 학습 자체가 True/False로 학습된 모델입니다.(이진분류) 따라서 multi-class 분류는 어렵고요. 다른 모델을 가져다 사용하시면 됩니다. 아래 예제 코드와 tutorial colab 파일 링크를 같이 공유 드립니다.

```python
from transformers import pipeline
nlp = pipeline("sentiment-analysis", 'bert-base-multilingual-uncased-sentiment')
result = nlp("I hate you")[0]
print(f"label: {result['label']}, with score: {round(result['score'], 4)}")
result = nlp("I love you")[0]
print(f"label: {result['label']}, with score: {round(result['score'], 4)}")

#label: 1 star, with score: 0.6346
#label: 5 stars, with score: 0.8547
```

```python
from transformers import ConvBertForSequenceClassification, ConvBertTokenizer

convBertModel = ConvBertForSequenceClassification.from_pretrained('bert-base-multilingual-uncased-sentiment', num_labels=25)
convBerttokenizer = ConvBertTokenizer.from_pretrained('bert-base-multilingual-uncased-sentiment')

print ( f"                              num_labels: {model.num_labels}")
print ( f"                              classifier: {model.classifier}")

# num_labels: 25
# classifier: ConvBertClassificationHead(
#   (dense): Linear(in_features=768, out_features=768, bias=True)
#   (dropout): Dropout(p=0.1, inplace=False)
#   (out_proj): Linear(in_features=768, out_features=25, bias=True)
# )
```


[text 분류 튜토리얼 코드(코랩)](https://colab.research.google.com/github/huggingface/notebooks/blob/master/examples/text_classification.ipynb#scrollTo=TlqNaB8jIrJW)
