### ISSUE TITLE
seq2seq 질문입니다!

### ISSUE THREAD

**Issue by tlsthk** [lovedlim/tensorflow#26]
우선 331 페이지에서 make_prediction 함수에서 매개변수?로 model, question_inputs 을 받는데,,
뒤페이지에 make_prediction을 실행하는 부분에서 매개변수가 앞에서 작성한 seq2seq, np.expand_dims(qeustion_inputs,0)이 어떻게 연결?이 되는 건지 이해가 안 가요 ㅠㅠ

전체적으로 이 코드가 어디서부터 시작해서 입력이 들어가서 모델이 학습되고 실행되는 건지를 모르겠습니다 ..

**Comment by tlsthk** [comment]
또 331 페이지에서 model.predicet를 안 하고 그냥 model()만 해도 예측이 가능한가요?

**Comment by teddylee777** [comment]
p.331에서
make_prediction 함수의 매개면수로 model과 question_inputs를 받고 있습니다
[코드]
def make_prediction(model, question_inputs)

그래서 seq2seq 모델이 make_prediction 함수의 첫번째 인자로 넘어가고, 
np.expand_dims(question_inputs, 0)을 하게 되면 1개의 차원이 증가하여 차원이 1개 증가된 question_inputs가 make_prediction의 두번째 인자로 들어가게 됩니다.

**Comment by teddylee777** [comment]
클래스 api 방식으로 모델을 생성한 경우 (p329의 Seq2Seq는 서브클래싱 방식(Sub Classing API)로 생성하고 있습니다)

model(입력데이터)를 넘겨 주게 되면, call()함수를 타면서 forward propagation (순전파 학습)을 진행합니다.

이에 대한 내용은 p114에서 다루고 있습니다. 참고해 주십쇼~
