### ISSUE TITLE
Functional API 

### ISSUE THREAD

**Issue by GentleKM** [lovedlim/tensorflow#28]
안녕하세요 :)

텍스트 분류 모델을 만들고 있는데 입력값 하나로는 성능이 많이 떨어져서, Functional API 활용 해보고 싶은데 자료가 많이 없더라구요.
혹시 Functional API 에 대해서 쉽고 자세하게 설명되어 있는 책이나 자료가 있을까요?

감사합니다.

**Comment by teddylee777** [comment]
책에서는 p.108에서 소개되어 있습니다.

좀 더 도움이 될 만한 링크를 공유 드리겠습니다.

- [텐서플로 튜토리얼](https://www.tensorflow.org/guide/keras/functional?hl=ko)
- [케라스 튜토리얼](https://keras.io/guides/functional_api/)
- [딥러닝을 활용한 자연어처리 입문 wikidocs](https://wikidocs.net/38861)

감사합니다.
