### ISSUE TITLE
6-2-2. 나만의 YOLO 모델 생성 오류

### ISSUE THREAD

**Issue by Haebuk** [lovedlim/tensorflow#3]
안녕하세요.
p223-4의 `make_img_label()` 함수에서 오류가 발생합니다:
```
error                                     Traceback (most recent call last)
<ipython-input-2-3d7b9083bc22> in <module>()
     43     return img,label
     44 
---> 45 img,label = make_img_label()
     46 cv2_imshow(img)

<ipython-input-2-3d7b9083bc22> in make_img_label()
     34             input_img = cv2.resize(img_0,(w,h))
     35         if(shape_type==1):
---> 36             input_img = cv2.resize(img_1,(w,h))
     37         if(shape_type==2):
     38             input_img = cv2.resize(img_2,(w,h))

error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/resize.cpp:3720: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
```

확인부탁드립니다:)

**Comment by HongJaeKwon** [comment]
안녕하세요.
공동저자 홍재권 이라고 합니다.
일단 코랩 기준으로 실행을 하셨는데 오류가 뜬다면,
책에서 설명 하였듯이 "0.png" / "1.png" / "2.png" 파일을 넣어주지 않아 생긴 오류 같습니다.
p223을 참조하여, 이미지 파일을 업로드 후 재 실행 부탁드립니다.
감사합니다.

**Comment by Haebuk** [comment]
![image](https://user-images.githubusercontent.com/68543150/127498629-96081de3-a2ad-4a5e-9cff-10a6056b81f6.png)

책의 사진과 동일한 것처럼 보이는데 혹시 업로드 경로가 잘못 됐을까요?
+ 혹시나 하고 다시 시도해봤는데 동일한 오류가 발생합니다 ㅠ

**Comment by HongJaeKwon** [comment]
![image](https://user-images.githubusercontent.com/44965354/127504696-37bce308-2c2a-41bc-999a-1cb31ba6ec34.png)

경로는 맞아보이는데, 혹시 이전 실행파일(darknet)이 남아있는걸 보면,
다른 예제파일에 올릴게 아닐까요?
제가 시험해 봤는데, 이상없이 실행이 됩니다.

**Comment by Haebuk** [comment]
챕터 6을 한 노트북에 몰아써서 해당 문제가 발생한거였군요. 
파일을 나누니 정상 작동합니다. 감사합니다:)

**Comment by HongJaeKwon** [comment]
앗 잘 해결되었다니 다행입니다.
한 노트북에 몰아도 동작이 이상해 질리는 없는데...
원인은 한번 저도 더 알아보겠습니다.
책을 보고 관심 가져 주셔서 감사합니다~!
