### ISSUE TITLE
320page [2] 실행시 http 404 error 발생....

### ISSUE THREAD

**Issue by digerati73** [lovedlim/tensorflow#31]
320page [2] 실행시 http 404 error 발생.... 합니다. 왜 그럴까요?

HTTPError                                 Traceback (most recent call last)
[<ipython-input-2-94b2bdf88166>](https://localhost:8080/#) in <module>()
      1 # 챗봇 라이브러리 불러오기
      2 from Korpora import KoreanChatbotKorpus
----> 3 corpus = KoreanChatbotKorpus()

9 frames
[/usr/lib/python3.7/urllib/request.py](https://localhost:8080/#) in http_error_default(self, req, fp, code, msg, hdrs)
    647 class HTTPDefaultErrorHandler(BaseHandler):
    648     def http_error_default(self, req, fp, code, msg, hdrs):
--> 649         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    650 
    651 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 404: Not Found

==> closed 된 issue 중에 있는데 다른 예제를 또 만들어 두셨군요...
그 예제의 코드로 대체 하면 될까요? 
지금 읽어 보고 있는중....

github repo에 올리신다는데 그건 또 먼지...

**Comment by teddylee777** [comment]
8번 issue에서 수정된 내용이 답변으로 달려 있습니다.
예제에 따라 수정된 방법으로 진행해 주시면 됩니다.

https://github.com/lovedlim/tensorflow/issues/8
--------
답변 내용:

Korpora PYPI 서버에 오류가 있어 보입니다.
원본 데이터셋의 raw 데이터를 직접 읽어와서 진행하실 수 있습니다.
work-around 하실 수 있는 코랩 예제파일의 링크를 공유 드리겠습니다. 수정된 코드를 참고해 주세요.

링크:
https://colab.research.google.com/drive/1c8DVe5lkMaJn6nUkmjVaNIom4FgKUqAi?usp=sharing
