### ISSUE TITLE
이 책의 정오표 자료는 어디에 있을까요?

### ISSUE THREAD

**Issue by digerati73** [lovedlim/tensorflow#32]
이 책의 정오표 자료는 어디에 있을까요?

**Comment by teddylee777** [comment]
GitHub 이슈에서 Closed 된 이슈중 Label을 "오탈자" 로 달아 놨습니다.
아래 링크 첨부 드리오니 참고 바랍니다.

https://github.com/lovedlim/tensorflow/issues?q=is%3Aclose+label%3A%EC%98%A4%EB%A5%98%2F%EC%98%A4%ED%83%88%EC%9E%90+
