### ISSUE TITLE
CNN 커널(필터) 개수

### ISSUE THREAD

**Issue by seohaa** [lovedlim/tensorflow#33]
CNN의 장점은 커널을 공유하기 때문에 훨씬 적은 가중치만 있어도 된다는 점이잖아요?
그런데 하나의 이미지에 대해 커널을 32개 사용하는 경우는 뭔가요.
왜 커널을 저렇게 많이 사용하는지, 그럼 CNN의 장점이 없어지는 거 아닌지 궁금합니다.

**Comment by teddylee777** [comment]
한 이미지에 대하여 32개의 서로 다른 특성 값을 추출하기 위함입니다.
