### ISSUE TITLE
[질문] 3단원 전체 질문입니다

### ISSUE THREAD

**Issue by JRgreed** [lovedlim/tensorflow#36]
1.
p.74
![image](https://user-images.githubusercontent.com/106368531/170804200-26982fe6-683a-447a-828a-05b194b2a36c.png)
왜 ax를 axes[i의 몫, i의 나머지] 이렇게 두는지 
왜 i의 몫과 나머지로 두는지 왜 5로 나누는지(즉, 3이나 4 등 다른 숫자가 안되는 이유)
가 궁금합니다

2.
p.75 
![image](https://user-images.githubusercontent.com/106368531/170803924-a895b2c9-4bc1-4a5c-ba65-5e887137ec86.png)
x_train[0, 10:15, 10:15] 이걸 뜻하는게 뭔지 궁금합니다
자세히 설명 부탁드립니다

3.
p.80
![image](https://user-images.githubusercontent.com/106368531/170804382-f31ff72b-f879-4b0d-b5c2-966ccff8f9ba.png)
여기서 input_shape=(28, 28)로 두셨는데 세로, 가로 형태까지인 것을 이해했는데 왜 이렇게 뒀는지(즉, 픽셀 갯수가 변수이고 Dense 레이어라서 이렇게 둔 것인지 그래서 input_shape=(784)로 두시지 않으신건지)

4.
p.84
![image](https://user-images.githubusercontent.com/106368531/170804029-c43cf8f6-6393-4cff-a711-d23a50188cda.png)
왜 1875인지 옆에 6s 3ms/step은 뭔지
![image](https://user-images.githubusercontent.com/106368531/170804159-afcf49c0-3fd8-409d-ab62-f782da05132d.png)
이것도 왜 313인지 설명 부탁드립니다

5.
p.85
![image](https://user-images.githubusercontent.com/106368531/170804949-6aeb5e07-8771-473b-a2df-c05e4a82939e.png)
첫번째 입력 이미지에 대한 분류 결과를 출력했는데 그러면 총 몇장이 있어 predictions[몇장] 까지 출력할 수 있는지 궁금합니다

**Comment by lovedlim** [comment]
1. 시각화 부분
5가 아닌 다른 숫자로도 얼마든지 가능합니다. 한 줄에 몇 개를 그리고자 하는 부분입니다.

**Comment by lovedlim** [comment]
2. 데이터 샘플 
df.head()와 비슷하게 일부 데이터를 나타낸 것이에요!

**Comment by lovedlim** [comment]
3. flatten레이어 역할
flatten는 2차원의 데이터를 1차원으로 변경합니다.
model.summary()를 확인해보면 flatten 출력이 784 인것을 확인할 수 있어요!

**Comment by lovedlim** [comment]
4. 배치 사이즈
배치 사이즈는 기본적으로 32입니다.
따라서 6만개의 데이터를 32로 나누면 1875가 되고
313은 테스트데이터의 수에서 나눠서 그렇습니다.

**Comment by lovedlim** [comment]
5. 출력
출력은 반복문 통해서 얼마든지 가능합니다 :) 
총 장수는 테스트 데이터 크기 입니다. 1만장

**Comment by JRgreed** [comment]
> 5. 출력
>    출력은 반복문 통해서 얼마든지 가능합니다 :)
>    총 장수는 테스트 데이터 크기 입니다. 1만장

3ms/step은 무슨 뜻인가요?

**Comment by JRgreed** [comment]
> 4. 배치 사이즈
>    배치 사이즈는 기본적으로 32입니다.
>    따라서 6만개의 데이터를 32로 나누면 1875가 되고
>    313은 테스트데이터의 수에서 나눠서 그렇습니다.

3ms/step 은 무슨 뜻인가요

**Comment by lovedlim** [comment]
시간입니다. 스탭별 밀리 초
