### ISSUE TITLE
개/고양이 분류 오류

### ISSUE THREAD

**Issue by moo1604** [lovedlim/tensorflow#4]
안녕하세요 이 책을 통해 tensorflow를 공부하고 있는 학생입니다.
다름이 아니라 개/고양이 분류실습을 하는데 kaggle에서 데이터셋을  구글 드라이브에 dataset 이라는 새로 만든 폴더에 다운받았더니 cat-and-dog.zip 이 아닌 archive.zip이라는 것이 나와서 압축해제를 하는 과정에서 경로설정후 archive.zip을 해주었는데 실행되지 않았고 그래서 따로 압축을 풀어 진행을 하였습니다.
그런데 flow_from_directory함수를 사용하여 폴더에서 이미지를 가져오는 과정에서 Found 0 images belonging to 2 classes.라고 나와 어떠한 문제때문인지 궁금하여 이렇게 글쓰게 되었습니다. 답변 부탁드립니다.
![cat-dog](https://user-images.githubusercontent.com/64899714/129820048-993327b7-837d-4560-82b4-32773b215699.PNG)

**Comment by lovedlim** [comment]
안녕하세요 :) 
올려주신 질문을 정리해보면 아래 두 가지 문제라고 보여집니다. 
1. 압축 해제 오류
2. 이미지 불러오기 오류
cat-and-dog.zip 이 아닌 archive.zip로 다운되면서 압축 해제 후 폴더 구조가 달라 발생한 문제입니다. 지금 kaggle에서 다운받아보니 archive.zip형태로 다운이 되네요! 이렇게 될 경우 경로 변경이 필요해요

글로 설명하기 보다 영상으로 보여드릴께요! 
https://youtu.be/ULlA8KSyh3U

## 변경전
train_dir = extract_folder + "archive/training_set/training_set"
valid_dir = extract_folder + "archive/test_set/test_set"

## 변경후
train_dir = extract_folder + "training_set/training_set"
valid_dir = extract_folder + "test_set/test_set"

**Comment by moo1604** [comment]
> 안녕하세요 :)
> 올려주신 질문을 정리해보면 아래 두 가지 문제라고 보여집니다.
> 
> 1. 압축 해제 오류
> 2. 이미지 불러오기 오류
>    cat-and-dog.zip 이 아닌 archive.zip로 다운되면서 압축 해제 후 폴더 구조가 달라 발생한 문제입니다. 지금 kaggle에서 다운받아보니 archive.zip형태로 다운이 되네요! 이렇게 될 경우 경로 변경이 필요해요
> 
> 글로 설명하기 보다 영상으로 보여드릴께요!
> https://youtu.be/ULlA8KSyh3U
> 
> ## 변경전
> train_dir = extract_folder + "archive/training_set/training_set"
> valid_dir = extract_folder + "archive/test_set/test_set"
> 
> ## 변경후
> train_dir = extract_folder + "training_set/training_set"
> valid_dir = extract_folder + "test_set/test_set"

**Comment by moo1604** [comment]
해결했습니다. 친절한 답변 감사드립니다.

네이버 메일앱에서 보냈습니다.
-----Original Message-----
보낸사람: "Kim Tae ***@***.***>
받는사람: ***@***.***>
참조: ***@***.***>, ***@***.***>
날짜: 2021. 8. 18 오전 11:24:33
제목: Re: [lovedlim/tensorflow] 개/고양이 분류 오류 (4)

안녕하세요 :)
올려주신 질문을 정리해보면 아래 두 가지 문제라고 보여집니다.

압축 해제 오류
이미지 불러오기 오류
cat-and-dog.zip 이 아닌 archive.zip로 다운되면서 압축 해제 후 폴더 구조가 달라 발생한 문제입니다. 지금 kaggle에서 다운받아보니 archive.zip형태로 다운이 되네요! 이렇게 될 경우 경로 변경이 필요해요

글로 설명하기 보다 영상으로 보여드릴께요!
https://youtu.be/ULlA8KSyh3U
변경전
train_dir = extract_folder + "archive/training_set/training_set"
valid_dir = extract_folder + "archive/test_set/test_set"
변경후
train_dir = extract_folder + "training_set/training_set"
valid_dir = extract_folder + "test_set/test_set"
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
