### ISSUE TITLE
[오류정정] 4.9 파일명에 관하여

### ISSUE THREAD

**Issue by skdding3** [lovedlim/tensorflow#5]
안녕하세요 책 너무 잘보고 있습니다!
다름이 아니라 별거 아닌 정정내용이겠지만,
4.9_style_trnasfer.ipynb 파일명이 style_transfer로 정정하는게 맞지않나라는 말씀 살포시 드립니다!

항상 잘 보고있습니다! 좋은 내용 책으로 내주셔서 너무 감사합니다

**Comment by lovedlim** [comment]
안녕하세요! 오타 알려주셔서 너무 감사드립니다. 불편을 드린 점에 대해서 사과 드립니다. 
덕분에 저희도 미처 발견하지 못한 오타를 알게되었네요!
말씀하신 파일명 4.9_style_trnasfer.ipynb 와 교재 p.258 부분에 오타가 있는 것 맞습니다. 
(단, 도서와의 일치를 위해 수정 출간 전까진 파일명을 그대로 두겠습니다.)

무한 성장하시길 응원하겠습니다. 화이팅하세요 👍 👍 👍
