### ISSUE TITLE
[오탈자] 47페이지 코드 결과

### ISSUE THREAD

**Issue by joonas-yoon** [lovedlim/tensorflow#6]
안녕하세요, 잘 읽고 있습니다.

p. 47 에서 3번 코드는 `range(1, EPOCHS + 1)` 이라서

EPOCH 0 은 나올 수 없는 출력인데, 책에는 아래와 같이 적혀있습니다.
```
EPOCH 0 - MSE: 5.1112 --- a: 0.17 --- b: 0.00
EPOCH 20 - MSE: 1.0654 --- a: 1.78 --- b: -0.79
...
```

노트북 코드를 `range(0, EPOCHS + 1)` 로 바꾸거나 해당 출력이 없어야한다고 생각했는데,

책에서 '_20번마다 중간 계산 결과를 ... 출력한다_ ' 라고 했으니 출력의 첫 줄(EPOCH 0 ...)이 오탈자로 보입니다. ([2.9_autodiff.ipynb](https://github.com/lovedlim/tensorflow/blob/main/Part%202/2.9_autodiff.ipynb) 파일의 출력도 그렇구요)

**Comment by lovedlim** [comment]
안녕하세요 :) 책 잘 읽고 계시다니 너무 감사드립니다.
네, 오타 맞습니다. 0출력이 없습니다.
저희가 꼼꼼히 수정 못했네요! 구체적으로 알려주셔서 감사드립니다 :) 

딥러닝 공부하며 무한 성장하시길 응원하겠습니다. 감사합니다.

**Comment by joonas-yoon** [comment]
이대로 close 하면 이후 개정에 반영이 되는건가요?

**Comment by teddylee777** [comment]
네 맞습니다. close 후 개정에 반영될 예정입니다. 개선에 참여해 주셔서 감사합니다 :)
