### ISSUE TITLE
[환경] 크롬 시크릿 모드에서 텐서 보드 403 Forbidden 에러

### ISSUE THREAD

**Issue by joonas-yoon** [lovedlim/tensorflow#7]
안녕하세요. 구글 크롬을 시크릿 모드로 사용하는 유저입니다. 

Part 3 에서 텐서보드를 띄우는 데 403 에러가 나와서 이슈로 남깁니다.

![Tensorboard 403 error](https://i.stack.imgur.com/TuHkS.png)

- 실습 환경 : 구글 코랩 + Chrome 브라우저 (시크릿 모드)
- 104 페이지 (발생한 오류와는 관계 없음. 하지만 이 페이지에서 마주함)

**해결:**

시크릿 모드에서 쿠키를 차단해서 생기는 오류였습니다. (설정 > 쿠키 및 기타 사이트 데이터 > 모든 쿠키 허용)

자체 해결했지만 코드 문제가 아니라 개발 환경 세팅 문제라 공유하고자 이슈로 남깁니다.

 https://stackoverflow.com/questions/64218755/getting-error-403-in-google-colab-with-tensorboard-with-firefox

**Comment by lovedlim** [comment]
안녕하세요 :) 
자세한 문제 상황과 구체적인 해결방안 너무 감사합니다 :) 
다음에 이런 상황 발생 시 쿠키 허용 옵션을 살펴보겠습니다.
감사드립니다:)
