### ISSUE TITLE
[질문] 챗봇 라이브러리 불러오기가 안됩니다.

### ISSUE THREAD

**Issue by yu901** [lovedlim/tensorflow#8]
320p 에 '챗봇 라이브러리 불러오기' 코드를 실행하면 HTTPError가 발생합니다.
![이미지 054](https://user-images.githubusercontent.com/28617311/133560727-590c3584-3474-4c7a-9160-80e85481aeae.png)

**Comment by teddylee777** [comment]
Korpora PYPI 서버에 오류가 있어 보입니다.
원본 데이터셋의 raw 데이터를 직접 읽어와서 진행하실 수 있습니다.
work-around 하실 수 있는 코랩 예제파일의 링크를 공유 드리겠습니다. 수정된 코드를 참고해 주세요.

링크:
https://colab.research.google.com/drive/1c8DVe5lkMaJn6nUkmjVaNIom4FgKUqAi?usp=sharing

**Comment by teddylee777** [comment]
github repo에도 colab 파일을 업로드 해두도록 하겠습니다.
