### ISSUE TITLE
[오탈자] 손실함수와 가준치의 편도함수 계산이 잘못됐습니다.

### ISSUE THREAD

**Issue by yu901** [lovedlim/tensorflow#9]
57페이지
손실함수 정의와 편도함수를 유도하는 과정에서 y_hat과  y 순서가 바뀌어야 식이 성립합니다.

**Comment by teddylee777** [comment]
hypothesis function이 wx + b로 저의 되어 있기 때문에 순서가 바뀌어야 깔끔하게 식이 성립합니다.
개정본시 반영하도록 하겠습니다.
감사합니다.
